### PR TITLE
Add layout, minumun styling, and add-score modules.

### PR DESCRIPTION
**Pull request by DiegoMero**
This pull request is to add the layout, and minimum styling to the page, and add-score functions to the project.

### CODE REVIEW

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @DiegoMero  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project to the wrong submission link on your dashboard. kindly check properly and submit again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DiegoMero** [comment]
Hi @vickymarz can you tell me why is it the wrong submission link?

**Comment by victorokoroji** [comment]
The task is for leaderboard project setup which is not reflected in your PR, I checked your pull requests and I found that the PR for the leaderboard setup has already been merged. You only have styling in your PR

**Comment by DiegoMero** [comment]
@vickymarz I deleted all the files from the dev, and now all my features that I want to merge into the dev branch are in the feature branch, did I request a new review now?

**Pull request closed without merging**
